# APISIX Configuration for ESPN Fantasy Baseball MCP Bridge
# Stand-alone mode configuration without etcd dependency

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

apisix:
  node_listen: 9080
  admin_listen:
    - ip: 0.0.0.0
      port: 9180
  enable_admin: false   # Disable admin API for production
  enable_dev_mode: true    # Enable hot-reload for development
  enable_reuseport: true
  enable_ipv6: false

nginx_config:
  error_log: "/usr/local/apisix/logs/error.log"
  error_log_level: "warn"
  worker_processes: "auto"
  worker_rlimit_nofile: 20480
  worker_connections: 10620
  http:
    access_log: "/usr/local/apisix/logs/access.log"
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    send_timeout: 10s
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_from:
      - 127.0.0.1
      - 'unix:'

# Plugin configuration
plugins:
  - cors
  - jwt-auth
  - limit-count
  - mcp-bridge      # our star
  - public-api      # exposes built-in utility paths like /apisix/status
  - node-status     # provides metrics for /apisix/status

# stream_plugins section removed because no stream plugins are in use

plugin_attr:
  prometheus:
    export_addr:
      ip: 127.0.0.1
      port: 9091