# Prometheus configuration for monitoring ESPN MCP Bridge

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # APISIX metrics
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    scrape_interval: 30s
    metrics_path: '/apisix/prometheus/metrics'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']